//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaniaDrift.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string Number { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Model Model { get; set; }
    }
}
