//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaniaDrift.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte[] Passport { get; set; }
        public byte[] INN { get; set; }
        public byte[] SNILS { get; set; }
        public byte[] DrivingLicense { get; set; }
    
        public virtual User User { get; set; }
    }
}
