//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlaniaDrift.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Car = new HashSet<Car>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BrandId { get; set; }
        public decimal AccelerationTime { get; set; }
        public int BodyId { get; set; }
        public int HorsePower { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Body Body { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Car> Car { get; set; }
    }
}
